import { injectable, inject } from 'inversify';
import { TYPES } from '../../../infrastructure/di/types';
import { ISubscriptionPlanRepository } from '../../../domain/repositories/ISubscriptionPlanRepository';
import { IUserRepository } from '../../../domain/repositories/IUserRepository';
import { SubscriptionPlan } from '../../../domain/entities/SubscriptionPlan';
import { CreateSubscriptionPlanDTO } from '../../dto/subscription/CreateSubscriptionPlanDTO';
import { ForbiddenError, ConflictError } from '../../../domain/errors/AppError';
import { UserRole } from '../../../domain/enums/UserRole';
import { ERROR_MESSAGES } from '../../../config/messages';
import { ICreateSubscriptionPlanUseCase } from './interfaces/ICreateSubscriptionPlanUseCase';
import { SubscriptionPlanDTO } from '../../dto/subscription/SubscriptionPlanDTO';
import { ISubscriptionPlanMapper } from '../../mappers/interfaces/ISubscriptionPlanMapper';

@injectable()
export class CreateSubscriptionPlanUseCase implements ICreateSubscriptionPlanUseCase {
  constructor(
    @inject(TYPES.IUserRepository) private userRepository: IUserRepository,
    @inject(TYPES.ISubscriptionPlanRepository) private subscriptionPlanRepository: ISubscriptionPlanRepository,
    @inject(TYPES.ISubscriptionPlanMapper) private subscriptionPlanMapper: ISubscriptionPlanMapper
  ) {}

  async execute(adminUserId: string, dto: CreateSubscriptionPlanDTO): Promise<SubscriptionPlanDTO> {
    // Verify admin privileges
    const adminUser = await this.userRepository.findById(adminUserId);
    if (!adminUser || adminUser.role !== UserRole.ADMIN) {
      throw new ForbiddenError(ERROR_MESSAGES.ADMIN.ACCESS_REQUIRED);
    }

    // Check if plan name already exists
    const existingPlan = await this.subscriptionPlanRepository.findByName(dto.name);
    if (existingPlan) {
      throw new ConflictError('A subscription plan with this name already exists');
    }

    // Generate feature IDs
    const features = dto.features.map((feature, index) => ({
      id: `${Date.now()}-${index}`,
      name: feature.name,
    }));

    // Create domain entity
    const plan = new SubscriptionPlan(
      '', // ID will be generated by database
      dto.name,
      dto.price,
      dto.projectPosts,
      dto.communityPosts,
      features,
      dto.badge as any,
      dto.color,
      true, // isActive
      new Date(),
      new Date()
    );

    // Save to repository
    const createdPlan = await this.subscriptionPlanRepository.create(plan);

    return this.subscriptionPlanMapper.toDTO(createdPlan);
  }
}
