export const TYPES = {
  Database: Symbol.for('Database'),
  RedisService: Symbol.for('RedisService'),
  IUserRepository: Symbol.for('IUserRepository'),
  IOTPRepository: Symbol.for('IOTPRepository'),
  IPasswordService: Symbol.for('IPasswordService'),
  IJWTService: Symbol.for('IJWTService'),
  IOTPService: Symbol.for('IOTPService'),
  IEmailService: Symbol.for('IEmailService'),
  IPendingRegistrationService: Symbol.for('IPendingRegistrationService'),
  PassportService: Symbol.for('PassportService'),
  RegisterUseCase: Symbol.for('RegisterUseCase'),
  LoginUseCase: Symbol.for('LoginUseCase'),
  VerifyOtpUseCase: Symbol.for('VerifyOtpUseCase'),
  ResendOtpUseCase: Symbol.for('ResendOtpUseCase'),
  AdminLoginUseCase: Symbol.for('AdminLoginUseCase'),
  GoogleAuthUseCase: Symbol.for('GoogleAuthUseCase'),
  ForgotPasswordUseCase: Symbol.for('ForgotPasswordUseCase'),
  VerifyForgotPasswordOtpUseCase: Symbol.for('VerifyForgotPasswordOtpUseCase'),
  ResetPasswordUseCase: Symbol.for('ResetPasswordUseCase'),
  
  ListUsersUseCase: Symbol.for('ListUsersUseCase'),
  SuspendUserUseCase: Symbol.for('SuspendUserUseCase'),
  UnsuspendUserUseCase: Symbol.for('UnsuspendUserUseCase'),
  GetUserProfileUseCase: Symbol.for('GetUserProfileUseCase'),
  UpdateUserProfileUseCase: Symbol.for('UpdateUserProfileUseCase'),
  
  ISubscriptionPlanRepository: Symbol.for('ISubscriptionPlanRepository'),
  
  ListSubscriptionPlansUseCase: Symbol.for('ListSubscriptionPlansUseCase'),
  ListPublicSubscriptionPlansUseCase: Symbol.for('ListPublicSubscriptionPlansUseCase'),
  GetSubscriptionStatsUseCase: Symbol.for('GetSubscriptionStatsUseCase'),
  CreateSubscriptionPlanUseCase: Symbol.for('CreateSubscriptionPlanUseCase'),
  UpdateSubscriptionPlanUseCase: Symbol.for('UpdateSubscriptionPlanUseCase'),
  DeleteSubscriptionPlanUseCase: Symbol.for('DeleteSubscriptionPlanUseCase'),
  
  AuthController: Symbol.for('AuthController'),
  AdminController: Symbol.for('AdminController'),
  SubscriptionController: Symbol.for('SubscriptionController'),
  PublicSubscriptionController: Symbol.for('PublicSubscriptionController'),
  UserProfileController: Symbol.for('UserProfileController'),
  
  AuthRoutes: Symbol.for('AuthRoutes'),
  AdminRoutes: Symbol.for('AdminRoutes'),
  SubscriptionRoutes: Symbol.for('SubscriptionRoutes'),
  PublicSubscriptionRoutes: Symbol.for('PublicSubscriptionRoutes'),
  UserProfileRoutes: Symbol.for('UserProfileRoutes'),
  
  App: Symbol.for('App'),
  
  IResponseBuilder: Symbol.for('IResponseBuilder'),

  
  ISkillRepository:Symbol.for('ISkillRepository'),
  IS3Service: Symbol.for('IS3Service'),
  CreateSkillUseCase: Symbol.for('CreateSkillUseCase'),
  ListUserSkillsUseCase: Symbol.for('ListUserSkillsUseCase'),
  BrowseSkillsUseCase: Symbol.for('BrowseSkillsUseCase'),
  BrowseSkillsController: Symbol.for('BrowseSkillsController'),
  BrowseSkillsRoutes: Symbol.for('BrowseSkillsRoutes'),
  GetSkillDetailsUseCase: Symbol.for('GetSkillDetailsUseCase'),
  SkillDetailsController: Symbol.for('SkillDetailsController'),
  SkillController: Symbol.for('SkillController'),
  SkillRoutes: Symbol.for('SkillRoutes'),

  
  ISkillTemplateRepository: Symbol.for('ISkillTemplateRepository'),
  CreateSkillTemplateUseCase: Symbol.for('CreateSkillTemplateUseCase'),
  ListSkillTemplatesUseCase: Symbol.for('ListSkillTemplatesUseCase'),
  UpdateSkillTemplateUseCase: Symbol.for('UpdateSkillTemplateUseCase'),
  DeleteSkillTemplateUseCase: Symbol.for('DeleteSkillTemplateUseCase'),
  ToggleSkillTemplateStatusUseCase: Symbol.for('ToggleSkillTemplateStatusUseCase'),
  SkillTemplateController: Symbol.for('SkillTemplateController'),
  SkillTemplateRoutes: Symbol.for('SkillTemplateRoutes'),
  PublicSkillTemplateRoutes: Symbol.for('PublicSkillTemplateRoutes'),

  
  ITemplateQuestionRepository: Symbol.for('ITemplateQuestionRepository'),
  CreateTemplateQuestionUseCase: Symbol.for('CreateTemplateQuestionUseCase'),
  ListTemplateQuestionsUseCase: Symbol.for('ListTemplateQuestionsUseCase'),
  UpdateTemplateQuestionUseCase: Symbol.for('UpdateTemplateQuestionUseCase'),
  DeleteTemplateQuestionUseCase: Symbol.for('DeleteTemplateQuestionUseCase'),
  TemplateQuestionController: Symbol.for('TemplateQuestionController'),
  TemplateQuestionRoutes: Symbol.for('TemplateQuestionRoutes'),

  // MCQ Tests
  IMCQRepository: Symbol.for('IMCQRepository'),
  StartMCQTestUseCase: Symbol.for('StartMCQTestUseCase'),
  SubmitMCQTestUseCase: Symbol.for('SubmitMCQTestUseCase'),
  GetMCQResultUseCase: Symbol.for('GetMCQResultUseCase'),
  MCQTestController: Symbol.for('MCQTestController'),
  MCQTestRoutes: Symbol.for('MCQTestRoutes'),

  // Admin Skill Management
  ListPendingSkillsUseCase: Symbol.for('ListPendingSkillsUseCase'),
  ApproveSkillUseCase: Symbol.for('ApproveSkillUseCase'),
  RejectSkillUseCase: Symbol.for('RejectSkillUseCase'),
  GetAllSkillsUseCase: Symbol.for('GetAllSkillsUseCase'),
  BlockSkillUseCase: Symbol.for('BlockSkillUseCase'),
  UnblockSkillUseCase: Symbol.for('UnblockSkillUseCase'),
  AdminSkillController: Symbol.for('AdminSkillController'),
  AdminSkillRoutes: Symbol.for('AdminSkillRoutes'),

  // Session Management
  IBookingRepository: Symbol.for('BookingRepository'),
  CreateBookingUseCase: Symbol.for('CreateBookingUseCase'),
  AcceptBookingUseCase: Symbol.for('AcceptBookingUseCase'),
  DeclineBookingUseCase: Symbol.for('DeclineBookingUseCase'),
  CancelBookingUseCase: Symbol.for('CancelBookingUseCase'),
  GetProviderBookingsUseCase: Symbol.for('GetProviderBookingsUseCase'),
  RescheduleBookingUseCase: Symbol.for('RescheduleBookingUseCase'),
  AcceptRescheduleUseCase: Symbol.for('AcceptRescheduleUseCase'),
  DeclineRescheduleUseCase: Symbol.for('DeclineRescheduleUseCase'),
  SessionManagementController: Symbol.for('SessionManagementController'),
  BookingController: Symbol.for('BookingController'),
  BookingRoutes: Symbol.for('BookingRoutes'),

  // Prisma Client
  PrismaClient: Symbol.for('PrismaClient'),
  IAdminUserDTOMapper: Symbol.for('IAdminUserDTOMapper'),
  IUserDTOMapper: Symbol.for('IUserDTOMapper'),
  IPendingSkillMapper: Symbol.for('IPendingSkillMapper'),
  ISubscriptionPlanMapper: Symbol.for('ISubscriptionPlanMapper'),
  IAuthResponseMapper: Symbol.for('IAuthResponseMapper'),
  ISkillMapper: Symbol.for('ISkillMapper'),
  IBrowseSkillMapper: Symbol.for('IBrowseSkillMapper'),
  ISkillDetailsMapper: Symbol.for('ISkillDetailsMapper'),
  IBookingMapper: Symbol.for('IBookingMapper')
};