export interface WeeklySchedule {
    [key: string]: {
        enabled: boolean;
        slots: { start: string; end: string }[];
    };
}

export interface BlockedDate {
    date: string;
    label?: string;
}

export class ProviderAvailability {
    constructor(
        public readonly id: string,
        public readonly providerId: string,
        public weeklySchedule: WeeklySchedule,
        public timezone: string,
        public bufferTime: number,
        public minAdvanceBooking: number,
        public maxAdvanceBooking: number,
        public autoAccept: boolean,
        public blockedDates: BlockedDate[],
        public maxSessionsPerDay?: number | null,
        public readonly createdAt?: Date,
        public readonly updatedAt?: Date
    ) { }

    static create(
        providerId: string,
        weeklySchedule: WeeklySchedule = {},
        timezone: string = 'UTC',
        bufferTime: number = 15,
        minAdvanceBooking: number = 24,
        maxAdvanceBooking: number = 30,
        autoAccept: boolean = false,
        blockedDates: BlockedDate[] = [],
        maxSessionsPerDay?: number | null
    ): ProviderAvailability {
        return new ProviderAvailability(
            '', // ID will be generated by DB
            providerId,
            weeklySchedule,
            timezone,
            bufferTime,
            minAdvanceBooking,
            maxAdvanceBooking,
            autoAccept,
            blockedDates,
            maxSessionsPerDay
        );
    }
}
